export const LIST_LENGTHS: readonly number[] = [4, 6, 8, 10, 15, 20, 25];
export const DEFAULT_LIST_LENGTH = 10;
export const SUBJECTS = [
  {
    id: 'any',
    label: 'Still exploring',
    codes: [] as string[],
    pattern: /undecided|still exploring|not sure what|no major/i,
  },
  {
    id: 'computing',
    label: 'Computer science',
    codes: ['11'],
    pattern:
      /computer science|comp(?:uter)? sci|\bCS\b|programming|coding|software|cybersecurity|artificial intelligence|data science/i,
  },
  {
    id: 'marine',
    label: 'Marine biology / science',
    codes: ['26', '40'],
    pattern: /marine (?:biology|science)|ocean(?:ography|s)?|aquatic/i,
  },
  {
    id: 'biology',
    label: 'Biology & life sciences',
    codes: ['26'],
    pattern: /biolog|biotech|biochem|pre[- ]?med|medicine|neuroscience/i,
  },
  { id: 'engineering', label: 'Engineering', codes: ['14'], pattern: /engineering|robotics/i },
  {
    id: 'business',
    label: 'Business',
    codes: ['52'],
    pattern: /business|entrepreneur|finance|accounting|marketing/i,
  },
  { id: 'psychology', label: 'Psychology', codes: ['42'], pattern: /psycholog|mental health/i },
  {
    id: 'arts',
    label: 'Visual & performing arts',
    codes: ['50'],
    pattern: /\bart\b|design|music|theat(?:er|re)|film|animation|dance/i,
  },
  {
    id: 'health',
    label: 'Health professions',
    codes: ['51'],
    pattern: /nursing|healthcare|health care|physical therapy|public health/i,
  },
  {
    id: 'environment',
    label: 'Environmental studies',
    codes: ['03'],
    pattern: /environment|sustainab|conservation|forestry/i,
  },
  { id: 'education', label: 'Education', codes: ['13'], pattern: /teaching|education|teacher/i },
  {
    id: 'social',
    label: 'Social sciences',
    codes: ['45'],
    pattern: /politic|sociolog|economics|international relations|anthropolog/i,
  },
  {
    id: 'math',
    label: 'Mathematics & statistics',
    codes: ['27'],
    pattern: /mathematics|\bmath\b|statistics/i,
  },
  {
    id: 'physical',
    label: 'Physical sciences',
    codes: ['40'],
    pattern: /physics|chemistry|astronomy|geolog/i,
  },
  {
    id: 'english',
    label: 'English & writing',
    codes: ['23'],
    pattern: /english|creative writing|literature/i,
  },
  {
    id: 'communication',
    label: 'Communication & journalism',
    codes: ['09'],
    pattern: /communication|journalism|public relations/i,
  },
  { id: 'history', label: 'History', codes: ['54'], pattern: /history|historian/i },
  {
    id: 'agriculture',
    label: 'Agriculture',
    codes: ['01'],
    pattern: /agricultur|animal science|veterinar/i,
  },
  { id: 'architecture', label: 'Architecture', codes: ['04'], pattern: /architectur/i },
] as const;
export const STATES: Record<string, string> = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  DC: 'District of Columbia',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
};
export const REGIONS: Record<string, string[]> = {
  northeast: ['CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA'],
  midwest: ['IN', 'IL', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD'],
  south: [
    'DE',
    'DC',
    'FL',
    'GA',
    'MD',
    'NC',
    'SC',
    'VA',
    'WV',
    'AL',
    'KY',
    'MS',
    'TN',
    'AR',
    'LA',
    'OK',
    'TX',
  ],
  west: ['AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA'],
};
export const NEIGHBORS: Record<string, string[]> = {
  AL: ['FL', 'GA', 'MS', 'TN'],
  AK: [],
  AZ: ['CA', 'NV', 'UT', 'NM', 'CO'],
  AR: ['LA', 'MS', 'MO', 'OK', 'TN', 'TX'],
  CA: ['AZ', 'NV', 'OR'],
  CO: ['AZ', 'KS', 'NE', 'NM', 'OK', 'UT', 'WY'],
  CT: ['MA', 'NY', 'RI'],
  DE: ['MD', 'NJ', 'PA'],
  DC: ['MD', 'VA'],
  FL: ['AL', 'GA'],
  GA: ['AL', 'FL', 'NC', 'SC', 'TN'],
  HI: [],
  ID: ['MT', 'NV', 'OR', 'UT', 'WA', 'WY'],
  IL: ['IN', 'IA', 'KY', 'MO', 'WI'],
  IN: ['IL', 'KY', 'MI', 'OH'],
  IA: ['IL', 'MN', 'MO', 'NE', 'SD', 'WI'],
  KS: ['CO', 'MO', 'NE', 'OK'],
  KY: ['IL', 'IN', 'MO', 'OH', 'TN', 'VA', 'WV'],
  LA: ['AR', 'MS', 'TX'],
  ME: ['NH'],
  MD: ['DC', 'DE', 'PA', 'VA', 'WV'],
  MA: ['CT', 'NH', 'NY', 'RI', 'VT'],
  MI: ['IN', 'OH', 'WI'],
  MN: ['IA', 'ND', 'SD', 'WI'],
  MS: ['AL', 'AR', 'LA', 'TN'],
  MO: ['AR', 'IL', 'IA', 'KS', 'KY', 'NE', 'OK', 'TN'],
  MT: ['ID', 'ND', 'SD', 'WY'],
  NE: ['CO', 'IA', 'KS', 'MO', 'SD', 'WY'],
  NV: ['AZ', 'CA', 'ID', 'OR', 'UT'],
  NH: ['ME', 'MA', 'VT'],
  NJ: ['DE', 'NY', 'PA'],
  NM: ['AZ', 'CO', 'OK', 'TX', 'UT'],
  NY: ['CT', 'MA', 'NJ', 'PA', 'VT'],
  NC: ['GA', 'SC', 'TN', 'VA'],
  ND: ['MN', 'MT', 'SD'],
  OH: ['IN', 'KY', 'MI', 'PA', 'WV'],
  OK: ['AR', 'CO', 'KS', 'MO', 'NM', 'TX'],
  OR: ['CA', 'ID', 'NV', 'WA'],
  PA: ['DE', 'MD', 'NJ', 'NY', 'OH', 'WV'],
  RI: ['CT', 'MA'],
  SC: ['GA', 'NC'],
  SD: ['IA', 'MN', 'MT', 'NE', 'ND', 'WY'],
  TN: ['AL', 'AR', 'GA', 'KY', 'MS', 'MO', 'NC', 'VA'],
  TX: ['AR', 'LA', 'NM', 'OK'],
  UT: ['AZ', 'CO', 'ID', 'NV', 'NM', 'WY'],
  VT: ['MA', 'NH', 'NY'],
  VA: ['DC', 'KY', 'MD', 'NC', 'TN', 'WV'],
  WA: ['ID', 'OR'],
  WV: ['KY', 'MD', 'OH', 'PA', 'VA'],
  WI: ['IL', 'IA', 'MI', 'MN'],
  WY: ['CO', 'ID', 'MT', 'NE', 'SD', 'UT'],
};
// A coarse preference boost, never a climate guarantee or a hard filter.
export const WARM_STATES = ['AL', 'AZ', 'CA', 'FL', 'GA', 'HI', 'LA', 'MS', 'NM', 'SC', 'TX'];
export const GEOGRAPHIES = [
  ['any', 'Anywhere in the US'],
  ['near-home', 'Home + neighboring states'],
  ['in-state', 'Home state only'],
  ['northeast', 'Northeast'],
  ['south', 'South'],
  ['midwest', 'Midwest'],
  ['west', 'West'],
] as const;
export const subjectLabel = (id: string) =>
  SUBJECTS.find((s) => s.id === id)?.label ?? 'Still exploring';
export const money = (n: number | null) =>
  n === null
    ? 'Not reported'
    : new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        maximumFractionDigits: 0,
      }).format(n);
export const percent = (n: number | null) =>
  n === null ? 'Not reported' : `${Math.round(n * 100)}%`;
export const scorecardUrl = (id: number) => `https://collegescorecard.ed.gov/school/?${id}`;
export const EXAMPLES = [
  {
    label: 'The hands-on programmer',
    detail: 'Computer science · Pennsylvania',
    text: "I have a student named John Smith, loves programming, won the Congressional App Challenge for the state of PA, 1230 SAT, 3.5 GPA, good AP scores like a 4 on Calc BC, 5 on Comp Sci A, 3 on Human Geo. Wants schools that aren't too far from home and are more practical and hands-on.",
  },
  {
    label: 'The ocean explorer',
    detail: 'Marine biology · Needs financial aid',
    text: 'Quiet kid, really into marine biology, middling test scores but a great story. Needs financial aid. Somewhere warm would be a plus.',
  },
  {
    label: 'The creative problem-solver',
    detail: 'Engineering · California',
    text: 'A student named Alex Rivera from California is interested in engineering and robotics. 1420 SAT, 3.8 GPA. Prefers public colleges in the West, hands-on learning, and needs financial aid.',
  },
];
